const mockAnamnese = {
  nome: "João Silva",
  telefone: "(11) 99999-9999",
  email: "joao@email.com",
  nascimento: "1990-05-10",
  endereco: "Rua Exemplo, 123",
  bairro: "Centro",
  cidade: "São Paulo",
  estado: "SP",
  cep: "01000-000",
  jaFezQuiropraxia: "Não",
  cirurgia: "Sim",
  usaMedicamento: "Sim",
  usoContinuo: "Não",
  cancer: "Não",
  gestante: "Não",
  fumante: "Não",
  atividadeFisica: "Sim",
  cardiaco: "Não",
  medicamentos: "Analgésico ocasional",
  movimentosDor: "Flexão do tronco",
  observacoes: "Dor lombar frequente",
};
export default mockAnamnese;